using System;
using System.Runtime.InteropServices;
using static System.Console;

public static class Program
{
    public static void Main(string[] args)
    {
        string message = "Dotnet-bot: Welcome to using .NET Core!";

        if (args.Length > 0)
        {
            message = String.Join(" ", args);
        }
        EmitBot(message);
        WriteLine("**Environment**");
        WriteLine($"Platform: .NET Core 1.0");
        WriteLine($"OS: {RuntimeInformation.OSDescription}");
        WriteLine();
    }

    public static void EmitBot(string message)
    {
        WriteLine($"\n    {message}");
        WriteLine(@"
    __________________
                      \
                       \
                          ....
                          ....'
                           ....
                        ..........
                    .............'..'..
                 ................'..'.....
               .......'..........'..'..'....
              ........'..........'..'..'.....
             .'....'..'..........'..'.......'.
             .'..................'...   ......
             .  ......'.........         .....
             .                           ......");
        Write("            ..    ");
        ConsoleColor origForeground = ForegroundColor;
        if (Environment.GetEnvironmentVariable("IsEvil") != null)
        {
            ForegroundColor = ConsoleColor.Red;
        }
        Write(".            ..");
        ForegroundColor = origForeground;
        WriteLine(@"        ......
           ....       .                 .......
           ......  .......          ............
            ................  ......................
            ........................'................
           ......................'..'......    .......
        .........................'..'.....       .......
     ........    ..'.............'..'....      ..........
   ..'..'...      ...............'.......      ..........
  ...'......     ...... ..........  ......         .......
 ...........   .......              ........        ......
.......        '...'.'.              '.'.'.'         ....
.......       .....'..               ..'.....
   ..       ..........               ..'........
          ............               ..............
         .............               '..............
        ...........'..              .'.'............
       ...............              .'.'.............
      .............'..               ..'..'...........
      ...............                 .'..............
       .........                        ..............
        .....

");
    }
}
